name: quality checks

on: push

jobs:
  black-lint:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -e ".[dev]"
      - run: black . --check
  ruff-lint:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -e ".[dev]"
      - run: ruff check .
  unit-test-python-310:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: [black-lint, ruff-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -e ".[dev]"
      - run: coverage run -a -m pytest tests/unit
  unit-test-python-311:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: [ black-lint, ruff-lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -e ".[dev]"
      - run: coverage run -a -m pytest tests/unit
  unit-test-python-312:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: [ black-lint, ruff-lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -e ".[dev]"
      - run: coverage run -a -m pytest tests/unit

