name: quality checks

on: push

jobs:
  ruff-lint:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -e ".[dev]"
      - run: ruff check .
  unit-test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    needs: [ruff-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" 
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" 
      - run: pip install tox
      - run: tox

